export const jamesCase = {
  conversationId: "CV-1001",
  leadId: "LD-2041",
  quoteId: "QT-2041",
  bookingId: "YRM-4120",
  operationId: "OP-4120",
  clientId: "james-miller",
  name: "James Miller",
  destinationId: "miami" as const,
  source: "Instagram",
  dates: "12–16 Nov",
  guests: 8,
  style: "Luxury Weekend",
  budget: "USD 10K–25K",
  interests: ["Yacht", "Dining", "Nightlife", "Transport"],
  total: 11950,
  supplierCost: 7400,
  margin: 4550,
  deposit: 5975,
  services: [
    {
      id: "j-yacht",
      service: "VanDutch 55",
      publicName: "Private Yacht",
      supplier: "Miami Yacht Partners",
      cost: 5000,
      sale: 7500,
    },
    {
      id: "j-transport",
      service: "Escalade / Chauffeur",
      publicName: "Luxury Transport",
      supplier: "Blackline Miami",
      cost: 450,
      sale: 750,
    },
    {
      id: "j-dining",
      service: "Dining Concierge",
      publicName: "Dining Concierge",
      supplier: "Dining Concierge",
      cost: 750,
      sale: 1700,
    },
    {
      id: "j-nightlife",
      service: "Nightlife Experience",
      publicName: "Nightlife Experience",
      supplier: "Nightlife Partner",
      cost: 1200,
      sale: 2000,
    },
  ],
};

export const jamesActivities = [
  { label: "Instagram message received", meta: "Sep 11 · 14:32" },
  { label: "Lead created", meta: "Sep 11 · 14:38" },
  { label: "Assigned to Sofía", meta: "Sep 11 · 14:40" },
  { label: "Internal note added", meta: "Sep 11 · 14:44" },
  { label: "Quote created", meta: "Sep 12 · 09:15" },
  { label: "Proposal sent", meta: "Sep 12 · 11:40" },
  { label: "Proposal accepted", meta: "Sep 12 · 12:18" },
  { label: "Booking confirmed", meta: "Sep 12 · 12:19" },
  { label: "Operation created", meta: "Sep 12 · 12:20" },
];
